### ISSUE TITLE
Implement Internationalization (i18n) in calculator

### ISSUE THREAD

**Issue by sedusa** [Pancreas-Digital/bolus-calculator#6]
## Purpose
Currently the `bolus-calculator` only supports the Spanish (Argentina) `es-AR` language.  The purpose of this ticket was enable support for other languages starting with support for the English `en-US` language.

## Approach (work to be done)
- [x] Implement i18n in the project using [Next.js's built-in support](https://nextjs.org/docs/advanced-features/i18n-routing)
- [x] Add support for the English language for now `en-US`
- [x] Translate text for modal (screenshots below)

<img width="1271" alt="modal" src="https://user-images.githubusercontent.com/5447546/190700281-915f24d9-f770-4669-b241-590e0ac6efa3.png">

- [x] Translate text for all the labels & input fields in the calculator app (screenshots below)

<img width="1274" alt="calculator" src="https://user-images.githubusercontent.com/5447546/190700437-3a462f56-3914-4d80-b35a-4b416229ff05.png">

- [x] Translate text for results (screenshots below)
- [x] Ensure that nothing is broken in the app and it works as expected

<img width="1275" alt="results" src="https://user-images.githubusercontent.com/5447546/190700538-70b4c0d9-ceaf-4cd4-beb4-ef9a7338a98e.png">

Attention @fedemotta

**Comment by fedemotta** [comment]
Nice addition for the project. Thank you so much for your help!

**Comment by sedusa** [comment]
@fedemotta is it possible to add me as a collaborator to this project? Currently I am unable to create a pull request.
Getting the following 403 error: 
```
remote: Permission to Pancreas-Digital/bolus-calculator.git denied to sedusa.
fatal: unable to access 'https://github.com/Pancreas-Digital/bolus-calculator.git/': The requested URL returned error: 403
```
Thanks!
